name: AntiCheatAddition
version: ${project.version}
description: ${project.description}
author: Photon
api-version: 1.19
website: https://www.spigotmc.org/resources/anticheataddition.33590/

depend:
  - packetevents
softdepend:
  - Floodgate
  - ViaVersion
  - WorldGuard

main: de.photon.anticheataddition.AntiCheatAddition

commands:
  anticheataddition:
    aliases: [ aca ]
    description: The main command of AntiCheatAddition.
    usage: /anticheataddition

permissions:
  anticheataddition.*:
    description: Allows to bypass all checks and clientcontrols and gives access to all commands and the debug system.
    children:
      anticheataddition.bypass.*: true
      anticheataddition.debug: true
      anticheataddition.info: true
      anticheataddition.internaltest: true
      anticheataddition.maincommand: true
      anticheataddition.setvl: true
    default: op

  anticheataddition.bypass.*:
    description: Players with this permission will not be checked by AntiCheatAddition.
    children:
      anticheataddition.bypass.sentinel.*: true
      anticheataddition.bypass.autoeat: true
      anticheataddition.bypass.autofish: true
      anticheataddition.bypass.autofish.parts.consistency: true
      anticheataddition.bypass.autofish.parts.inhuman_reaction: true
      anticheataddition.bypass.autopotion: true
      anticheataddition.bypass.duping: true
      anticheataddition.bypass.duping.parts.double_dropped: true
      anticheataddition.bypass.duping.parts.secretcache: true
      anticheataddition.bypass.damageindicator: true
      anticheataddition.bypass.esp: true
      anticheataddition.bypass.fastswitch: true
      anticheataddition.bypass.impossiblechat: true
      anticheataddition.bypass.informationhider: true
      anticheataddition.bypass.informationhider.parts.enchantments: true
      anticheataddition.bypass.informationhider.parts.item_count: true
      anticheataddition.bypass.inventory: true
      anticheataddition.bypass.inventory.parts.averageheuristic: true
      anticheataddition.bypass.inventory.parts.hit: true
      anticheataddition.bypass.inventory.parts.move: true
      anticheataddition.bypass.inventory.parts.multiinteraction: true
      anticheataddition.bypass.inventory.parts.perfectexit: true
      anticheataddition.bypass.inventory.parts.rotation: true
      anticheataddition.bypass.inventory.parts.sprinting: true
      anticheataddition.bypass.inventory.parts.statistical: true
      anticheataddition.bypass.packetanalysis: true
      anticheataddition.bypass.packetanalysis.parts.animation: true
      anticheataddition.bypass.packetanalysis.parts.equalrotation: true
      anticheataddition.bypass.packetanalysis.parts.illegalpitch: true
      anticheataddition.bypass.packetanalysis.parts.perfectrotation: true
      anticheataddition.bypass.scaffold: true
      anticheataddition.bypass.scaffold.parts.angle: true
      anticheataddition.bypass.scaffold.parts.face: true
      anticheataddition.bypass.scaffold.parts.jumping: true
      anticheataddition.bypass.scaffold.parts.position: true
      anticheataddition.bypass.scaffold.parts.rotation: true
      anticheataddition.bypass.scaffold.parts.safewalk.edge: true
      anticheataddition.bypass.scaffold.parts.safewalk.timing: true
      anticheataddition.bypass.scaffold.parts.sprinting: true
      anticheataddition.bypass.shield: true
      anticheataddition.bypass.shield.parts.hit: true
      anticheataddition.bypass.skinblinker: true
      anticheataddition.bypass.skinblinker.parts.sprinting: true
      anticheataddition.bypass.skinblinker.parts.unusedbit: true
      anticheataddition.bypass.teaming: true
      anticheataddition.bypass.tower: true

  anticheataddition.bypass.sentinel.*:
    description: Bypasses all sentinel modules. Make sure to have a permission plugin to actually bypass all sentinel modules.

  anticheataddition.debug:
    description: This allows the player to see highly detailed information about violations if enabled in the config.

  anticheataddition.info:
    description: Allows requesting an overview about a player's violation levels

  anticheataddition.internaltest:
    description: Allows testing various AntiCheatAddition checks by spoofing cheat behaviour. This is not intended for normal use and can be used to falsely flag players.

  anticheataddition.maincommand:
    description: Allows the player to execute the main command of AntiCheatAddition and see the current plugin version.
    permission-message: Unknown command. Type "/help" for help.

  anticheataddition.setvl:
    description: Allows the player to execute a command which will set the vl of another player, usually used for testing.