name: AntiCheatAddition
version: ${project.version}
description: ${project.description}
author: Photon
api-version: 1.15
website: https://www.spigotmc.org/resources/anticheataddition.33590/

depend: [ ProtocolLib ]
softdepend: [ ViaVersion , Floodgate ]
main: de.photon.anticheataddition.AntiCheatAddition

commands:
  anticheataddition:
    aliases: [ aca ]
    description: The main command of AntiCheatAddition.
    usage: /anticheataddition

permissions:
  anticheataddition.*:
    description: Allows to bypass all checks and clientcontrols and gives access to all commands and the debug system.
    children:
      anticheataddition.bypass.*: true
      anticheataddition.debug: true
      anticheataddition.info: true
      anticheataddition.internaltest: true
      anticheataddition.setvl: true
    default: op

  anticheataddition.bypass.*:
    description: Players with this permission will not be checked by AntiCheatAddition.
    children:
      anticheataddition.bypass.sentinel.*: true
      anticheataddition.bypass.anticheataddition_autoeat: true
      anticheataddition.bypass.anticheataddition_autofish: true
      anticheataddition.bypass.anticheataddition_autofish.parts.consistency: true
      anticheataddition.bypass.anticheataddition_autofish.parts.inhuman_reaction: true
      anticheataddition.bypass.anticheataddition_autopotion: true
      anticheataddition.bypass.anticheataddition_duping: true
      anticheataddition.bypass.anticheataddition_duping.parts.double_dropped: true
      anticheataddition.bypass.anticheataddition_duping.parts.secretcache: true
      anticheataddition.bypass.anticheataddition_damageindicator: true
      anticheataddition.bypass.anticheataddition_enchantmenthider: true
      anticheataddition.bypass.anticheataddition_esp: true
      anticheataddition.bypass.anticheataddition_fastswitch: true
      anticheataddition.bypass.anticheataddition_impossiblechat: true
      anticheataddition.bypass.anticheataddition_inventory: true
      anticheataddition.bypass.anticheataddition_inventory.parts.averageheuristic: true
      anticheataddition.bypass.anticheataddition_inventory.parts.hit: true
      anticheataddition.bypass.anticheataddition_inventory.parts.move: true
      anticheataddition.bypass.anticheataddition_inventory.parts.multiinteraction: true
      anticheataddition.bypass.anticheataddition_inventory.parts.perfectexit: true
      anticheataddition.bypass.anticheataddition_inventory.parts.rotation: true
      anticheataddition.bypass.anticheataddition_inventory.parts.sprinting: true
      anticheataddition.bypass.anticheataddition_packetanalysis: true
      anticheataddition.bypass.anticheataddition_packetanalysis.parts.animation: true
      anticheataddition.bypass.anticheataddition_packetanalysis.parts.equalrotation: true
      anticheataddition.bypass.anticheataddition_packetanalysis.parts.illegalpitch: true
      anticheataddition.bypass.anticheataddition_pingspoof: true
      anticheataddition.bypass.anticheataddition_scaffold: true
      anticheataddition.bypass.anticheataddition_scaffold.parts.angle: true
      anticheataddition.bypass.anticheataddition_scaffold.parts.jumping: true
      anticheataddition.bypass.anticheataddition_scaffold.parts.position: true
      anticheataddition.bypass.anticheataddition_scaffold.parts.rotation.derivative: true
      anticheataddition.bypass.anticheataddition_scaffold.parts.rotation.fastChange: true
      anticheataddition.bypass.anticheataddition_scaffold.parts.rotation.secondderivative: true
      anticheataddition.bypass.anticheataddition_scaffold.parts.safewalk.type1: true
      anticheataddition.bypass.anticheataddition_scaffold.parts.safewalk.type2: true
      anticheataddition.bypass.anticheataddition_scaffold.parts.sprinting: true
      anticheataddition.bypass.anticheataddition_shield: true
      anticheataddition.bypass.anticheataddition_shield.parts.hit: true
      anticheataddition.bypass.anticheataddition_skinblinker: true
      anticheataddition.bypass.anticheataddition_skinblinker.parts.sprinting: true
      anticheataddition.bypass.anticheataddition_skinblinker.parts.unusedbit: true
      anticheataddition.bypass.teaming: true
      anticheataddition.bypass.tower: true

  anticheataddition.bypass.sentinel.*:
    description: Bypasses all sentinel modules. Make sure to have a permission plugin to actually bypass all sentinel modules.

  anticheataddition.debug:
    description: This allows the player to see highly detailed information about violations if enabled in the config.

  anticheataddition.info:
    description: Allows requesting an overview about a player's violation levels

  anticheataddition.internaltest:
    description: Allows testing various AntiCheatAddition checks by spoofing cheat behaviour. This is not intended for normal use and can be used to falsely flag players.

  anticheataddition.setvl:
    description: Allows the player to execute a command which will set the vl of another player, usually used for testing.