package de.photon.anticheataddition.util.mathematics;

import com.google.common.base.Preconditions;
import com.google.common.primitives.Doubles;
import com.google.common.primitives.Longs;
import lombok.experimental.UtilityClass;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.math.MathContext;
import java.util.Arrays;

/**
 * Kolmogorov-Smirnov helper utilities for comparing a sample's shape against a uniform distribution.
 *
 * <p>The public {@code uniformTest(...)} methods first rescale the observed values to the sample's own
 * {@code [min, max]} range, then compute the two-sided KS statistic against {@code U(0, 1)}. Because the range is
 * estimated from the same sample, the returned p-value should be treated as an approximate heuristic score, not as an
 * exact formal one-sample KS p-value for a pre-specified distribution.</p>
 *
 * <p>Typical workflow:
 * <pre>{@code
 * double[] samples = ...;
 * boolean ok = KolmogorovSmirnov.uniformTest(samples).significanceTest(0.05);
 * }</pre>
 */
@UtilityClass
public final class KolmogorovSmirnov
{

    private static final int MAX_P_VALUE_TERMS = 1000;
    private static final double P_VALUE_EPSILON = 1e-12;
    private static final double EFFECTIVELY_CERTAIN_P_VALUE_LAMBDA = 1e-2;

    /**
     * Computes the two-sided KS statistic and approximate p-value for doubles after rescaling to the sample's own range.
     */
    public static KsResult uniformTest(double[] sample)
    {
        double[] norm = normalize(sample);
        return testSortedNormalized(norm);
    }

    /**
     * Computes the two-sided KS statistic and approximate p-value for longs after rescaling to the sample's own range.
     */
    public static KsResult uniformTest(long[] sample)
    {
        double[] norm = normalize(sample);
        return testSortedNormalized(norm);
    }

    /**
     * Immutable result of a two-sided Kolmogorov-Smirnov test.
     *
     * <p>Notation:</p>
     * <ul>
     *   <li>{@code dStatistic} - the Kolmogorov-Smirnov <em>D</em> statistic
     *       <br>D = sup<sub>x</sub>|F<sub>n</sub>(x) - F<sub>0</sub>(x)|, range 0...1.</li>
     *   <li>{@code pValue} - approximate two-sided tail probability from the asymptotic KS distribution after a
     *       finite-sample correction.</li>
     * </ul>
     *
     * <p>Interpretation: A <strong>large D</strong> or small p-value signals that the empirical CDF deviates strongly
     * from the ideal CDF. A large p-value only means that the uniform shape was not rejected by this heuristic; it is
     * not the probability that the sample was generated by a uniform distribution.</p>
     *
     * @param dStatistic Kolmogorov-Smirnov D statistic.
     * @param pValue     approximate two-sided p-value.
     */
    public record KsResult(double dStatistic, double pValue)
    {
        /**
         * Decision helper for threshold-style use.
         *
         * @param alpha significance level in (0, 1), e.g. 0.05 for 95% confidence
         *
         * @return {@code true} iff {@code pValue >= alpha}
         */
        public boolean significanceTest(double alpha)
        {
            Preconditions.checkArgument(alpha > 0 && alpha < 1, "alpha must be in (0,1)");
            return pValue >= alpha;
        }
    }

    /**
     * Normalizes finite doubles to {@code [0, 1]} using their sample minimum and maximum, then sorts ascending.
     */
    public static double[] normalize(double[] data)
    {
        Preconditions.checkNotNull(data, "data must not be null");
        if (data.length == 0) return new double[0];
        for (double datum : data) {
            Preconditions.checkArgument(Double.isFinite(datum), "data must contain only finite values");
        }

        double min = Doubles.min(data);
        double max = Doubles.max(data);
        if (min == max) return new double[data.length];

        return Arrays.stream(data)
                     .map(x -> normalizeFiniteDouble(x, min, max))
                     .sorted()
                     .toArray();
    }

    /**
     * Normalizes longs to {@code [0, 1]} using their sample minimum and maximum, then sorts ascending.
     */
    public static double[] normalize(long[] data)
    {
        Preconditions.checkNotNull(data, "data must not be null");
        if (data.length == 0) return new double[0];

        long min = Longs.min(data);
        long max = Longs.max(data);
        if (min == max) return new double[data.length];

        try {
            long range = Math.subtractExact(max, min);
            return Arrays.stream(data)
                         .mapToDouble(x -> (x - min) / (double) range)
                         .sorted()
                         .toArray();
        } catch (ArithmeticException ignored) {
            // The full long range does not fit into a signed long. Use decimal arithmetic only for this rare case.
            BigDecimal minDecimal = BigDecimal.valueOf(min);
            BigDecimal range = new BigDecimal(BigInteger.valueOf(max).subtract(BigInteger.valueOf(min)));
            return Arrays.stream(data)
                         .mapToDouble(x -> BigDecimal.valueOf(x)
                                                     .subtract(minDecimal)
                                                     .divide(range, MathContext.DECIMAL64)
                                                     .doubleValue())
                         .sorted()
                         .toArray();
        }
    }

    private static double normalizeFiniteDouble(double value, double min, double max)
    {
        double range = max - min;
        if (Double.isFinite(range)) return (value - min) / range;

        double halfMin = min * 0.5;
        return (value * 0.5 - halfMin) / (max * 0.5 - halfMin);
    }

    private static KsResult testSortedNormalized(double[] sortedNorm)
    {
        final int n = sortedNorm.length;
        Preconditions.checkArgument(n > 1, "The KS test requires at least 2 data points");

        final double d = ksStatistic(sortedNorm);
        final double sqrtN = Math.sqrt(n);
        final double lambda = (sqrtN + 0.12 + 0.11 / sqrtN) * d;
        final double p = ksPValue(lambda);
        return new KsResult(d, p);
    }

    /** Two-sided D = sup|F_n(x) - x| for sorted values in [0, 1]. */
    private static double ksStatistic(double[] x)
    {
        final int n = x.length;
        double max = 0.0;
        for (int i = 0; i < n; i++) {
            double empUp = (i + 1.0) / n;
            double empDown = i / (double) n;
            double diffUp = Math.abs(empUp - x[i]);
            double diffDown = Math.abs(x[i] - empDown);
            max = Math.max(max, Math.max(diffUp, diffDown));
        }
        return max;
    }

    /**
     * Asymptotic two-sided KS tail probability:
     * Q_KS(lambda) = 2 * sum((-1)^(j-1) * exp(-2 * j^2 * lambda^2)).
     */
    private static double ksPValue(double lambda)
    {
        if (lambda < EFFECTIVELY_CERTAIN_P_VALUE_LAMBDA) return 1.0;

        double sum = 0.0;
        for (int j = 1; j <= MAX_P_VALUE_TERMS; j++) {
            double sign = (j & 1) == 1 ? 1.0 : -1.0;
            double term = 2.0 * sign * Math.exp(-2.0 * j * j * lambda * lambda);
            sum += term;
            if (Math.abs(term) < P_VALUE_EPSILON) break;
        }
        return Math.clamp(sum, 0.0, 1.0);
    }
}
