package de.photon.aacadditionproold.user;

import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum TimestampKey
{
    AUTOEAT_TIMEOUT,

    AUTOFISH_DETECTION,

    AUTOPOTION_DETECTION,
    AUTOPOTION_TIMEOUT,

    INVENTORY_OPENED,

    LAST_COMBAT,
    LAST_CONSUME_EVENT,
    LAST_FISH_BITE,
    LAST_HEAD_OR_OTHER_MOVEMENT,
    LAST_HOTBAR_SWITCH,
    LAST_INVENTORY_CLICK,
    LAST_INVENTORY_CLICK_ON_ITEM,
    LAST_RESPAWN,
    LAST_RIGHT_CLICK_CONSUMABLE_ITEM_EVENT,
    LAST_RIGHT_CLICK_EVENT,
    LAST_SLOT_CLICKED,
    LAST_SNEAK_DURATION,
    LAST_SNEAK_TOGGLE,
    LAST_SPRINT_DURATION,
    LAST_SPRINT_TOGGLE,
    LAST_TELEPORT,
    LAST_VELOCITY_CHANGE,
    LAST_VELOCITY_CHANGE_NO_EXTERNAL_CAUSES,
    LAST_WORLD_CHANGE,
    LAST_XYZ_MOVEMENT,
    LAST_XZ_MOVEMENT,

    LOGIN_TIME,

    PACKET_ANALYSIS_LAST_COMPARE_FLAG,
    PACKET_ANALYSIS_LAST_POSITION_FORCE,

    SCAFFOLD_SIGNIFICANT_ROTATION_CHANGE,

    SCAFFOLD_TIMEOUT,

    TEAMING_COMBAT_TAG,

    TOWER_SLIME_JUMP,
    TOWER_TIMEOUT
}
