package de.photon.aacadditionpro.user;

import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum TimestampKey
{
    AUTOEAT_TIMEOUT,

    AUTOFISH_DETECTION,

    AUTOPOTION_DETECTION,
    AUTOPOTION_LAST_SUDDEN_PITCH,
    AUTOPOTION_LAST_SUDDEN_YAW,
    AUTOPOTION_TIMEOUT,

    INVENTORY_OPENED,

    LAST_COMBAT,
    LAST_CONSUME_EVENT,
    LAST_FISH_BITE,
    LAST_HEAD_MOVEMENT,
    LAST_INVENTORY_CLICK,
    LAST_RESPAWN,
    LAST_RIGHT_CLICK_CONSUMABLE_ITEM_EVENT,
    LAST_RIGHT_CLICK_EVENT,
    LAST_SLOT_CLICKED,
    LAST_SNEAK,
    LAST_SNEAK_DURATION,
    LAST_SPRINT,
    LAST_SPRINT_DURATION,
    LAST_TELEPORT,
    LAST_VELOCITY_CHANGE,
    LAST_WORLD_CHANGE,
    LAST_XYZ_MOVEMENT,
    LAST_XZ_MOVEMENT,

    LOGIN_TIME,

    PACKET_ANALYSIS_LAST_COMPARE_FLAG,
    PACKET_ANALYSIS_LAST_POSITION_FORCE,

    PINGSPOOF_DETECTION,

    SCAFFOLD_SIGNIFICANT_ROTATION_CHANGE,

    TOWER_TIMEOUT
}
